[mypy]
ignore_missing_imports = True
allow_untyped_defs = True
allow_untyped_calls = True
allow_untyped_globals = True
implicit_optional = True
disable_error_code = var-annotated,assignment,union-attr,type-var,arg-type,attr-defined,index,import,operator
